sudo: false
dist: trusty
language: c
compiler:
  - gcc
addons:
  apt:
    packages:
    - libreadline6-dev
    - libncurses5-dev
    - perl
    - clang
env:
 - BASE=3.16 STATIC=shared TEST=YES
 - BASE=3.16 STATIC=static RTEMS=4.9
 - BASE=3.16 STATIC=shared CMPLR=clang RTEMS=4.10
 - BASE=3.15 STATIC=shared
 - BASE=3.14 STATIC=shared
 - BASE=R3.14.12.2 STATIC=shared
install: .ci/travis-prepare.sh
script: .ci/travis-build.sh
